services:
  app:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 5678:5678
    volumes:
      - ./data/aanvraagapp.db:/app/aanvraagapp.db
      - .:/app
    depends_on:
      - redis
  redis:
    platform: linux/amd64
    image: "redis:alpine"
    ports:
      - 6379:6379
  mail:
    platform: linux/amd64
    image: mailhog/mailhog
    ports:
      - 1025:1025 # SMTP server
      - 8025:8025 # Web UI
  adminer:
    platform: linux/amd64
    image: adminer:5.3.0
    # TODO: Fix in a better way: https://github.com/TimWolla/docker-adminer/issues/167
    user: root  # Otherwise Adminer cannot update records in sqlite...
    ports:
      - 8080:8080
    volumes:
      - ./data/aanvraagapp.db:/app/aanvraagapp.db
      - ../adminer-plugin-sqlite/sqlite.php:/var/www/html/sqlite.php
      - ../adminer-plugin-sqlite/plugins:/var/www/html/plugins
