services:
  app:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 5678:5678
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - ENVIRONMENT=local.container
  redis:
    platform: linux/amd64
    image: "redis:alpine"
    ports:
      - 6379:6379
  mail:
    platform: linux/amd64
    image: mailhog/mailhog
    ports:
      - 1025:1025 # SMTP server
      - 8025:8025 # Web UI
  adminer:
    platform: linux/amd64
    image: adminer:5.3.0
    ports:
      - 8080:8080
  db:
    platform: linux/amd64
    image: pgvector/pgvector:pg17-trixie
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES__USER}"]
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./init_db:/docker-entrypoint-initdb.d:ro
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: mark
      POSTGRES_USER: mark
      POSTGRES_DB: mark
    # usefull for debugging postgres queries!
    # command: ["postgres", "-c", "log_statement=all"]
volumes:
  postgres_data: